- name: Super-Linter
  uses: github/super-linter@v2.1.0

on:
  push:
      - 'master'

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.1
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false
          VALIDATE_PYTHON: false
          VALIDATE_DOCKER: false
          VALIDATE_GO: false
          VALIDATE_TERRAFORM: false
          VALIDATE_COFFEE: false
