name: Lint

on: 
  pull_request:
    branches:
      - master
      - dev

jobs:
  run-linters-and-tests:
    name: Run linters and tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run linters
        run: npm run lint